name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '*.tf'                          # <-- Watches main.tf (and any other .tf files) in the root
      - 'lambda/**'                     # <-- Watches your Python Lambda code folder
      - '.github/workflows/backend.yaml' # <-- Runs if you edit this workflow file
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Pull down the code from GitHub
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # 3. Install dependencies & Run Unit Tests
    - name: Run Python Unit Tests
      env:
        AWS_DEFAULT_REGION: eu-north-1
      run: |
        pip install boto3
        cd lambda
        python -m unittest test_lambda.py

    # 4. Configure AWS Credentials from GitHub Secrets
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    # 5. Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    # 6. Initialize Terraform (Forces S3 backend sync)
    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-1
      run: terraform init -reconfigure -input=false

    # 7. Terraform Plan
    - name: Terraform Plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-1
      run: terraform plan -input=false

    # 8. Terraform Apply
    - name: Terraform Apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-1
      run: terraform apply -auto-approve -input=false
        