name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # 1. Sync website files to S3
    - name: Sync S3 Bucket
      run: |
        aws s3 sync ./ s3://nitin-cloud-resume-bucket-2026 --exclude ".git/*" --exclude ".github/*" --exclude "terraform/*" --exclude "lambda/*" --delete

    # 2. Invalidate CloudFront Cache
    - name: Invalidate CloudFront Cache
      run: |
        DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items && contains(Aliases.Items, 'nitincloud.co.uk')].Id | [0]" --output text)
        if [ "$DIST_ID" != "None" ] && [ -n "$DIST_ID" ]; then
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
        else
          echo "No CloudFront distribution found for nitincloud.co.uk, skipping invalidation."
        fi
